
Neos:
  # To detect race conditions, enable the code block below, and set raceConditionTracker.enabled to TRUE
  # and then use ./flow raceConditionTracker:analyzeTrace
  #ContentRepositoryRegistry:
  #  presets:
  #    'default':
  #        contentGraphProjection:
  #          catchUpHooks:
  #            'Neos.ContentRepository.BehavioralTests:RaceConditionTracker':
  #              factoryObjectName: Neos\ContentRepository\BehavioralTests\ProjectionRaceConditionTester\RaceTrackerCatchUpHookFactory

  ContentRepository:
    BehavioralTests:
      raceConditionTracker:
        enabled: false
        redis:
          host: 127.0.0.1
          port: 6379

  ContentRepositoryRegistry:
    contentRepositories:
      test_parallel:
        eventStore:
          factoryObjectName: Neos\ContentRepositoryRegistry\Factory\EventStore\DoctrineEventStoreFactory
        nodeTypeManager:
          factoryObjectName: Neos\ContentRepository\BehavioralTests\TestSuite\Behavior\GherkinPyStringNodeBasedNodeTypeManagerFactory
        contentDimensionSource:
          factoryObjectName: Neos\ContentRepository\BehavioralTests\TestSuite\Behavior\GherkinTableNodeBasedContentDimensionSourceFactory
        authProvider:
          factoryObjectName: Neos\ContentRepositoryRegistry\Factory\AuthProvider\StaticAuthProviderFactory
        clock:
          factoryObjectName: Neos\ContentRepositoryRegistry\Factory\Clock\SystemClockFactory
        subscriptionStore:
          factoryObjectName: Neos\ContentRepositoryRegistry\Factory\SubscriptionStore\SubscriptionStoreFactory
        propertyConverters: {}
        contentGraphProjection:
          factoryObjectName: Neos\ContentGraph\DoctrineDbalAdapter\DoctrineDbalContentGraphProjectionFactory

  Flow:
    object:
      includeClasses:
        # do NOT include PhpstanRules here
        'Neos.ContentRepository.BehavioralTests': [ 'Neos\\ContentRepository\\BehavioralTests\\(Command|ProjectionRaceConditionTester)' ]
