Neos:
  ContentRepositoryRegistry:
    presets:
      default:
        userIdProvider:
          factoryObjectName: 'Neos\ContentRepository\TestSuite\Fakes\FakeUserIdProviderFactory'
        clock:
          factoryObjectName: 'Neos\ContentRepository\TestSuite\Fakes\FakeClockFactory'
        nodeTypeManager:
          factoryObjectName: 'Neos\ContentRepository\TestSuite\Fakes\FakeNodeTypeManagerFactory'
        contentDimensionSource:
          factoryObjectName: 'Neos\ContentRepository\TestSuite\Fakes\FakeContentDimensionSourceFactory'
